apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: demo2
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
        flux.weave.works/automated: "true"
        flux.weave.works/tag.nginx: semver:~8.5
    spec:
      containers:
      - name: tomcat
        image: sshaik/tomcat:8.5.55-jdk11
        ports:
        - containerPort: 8080
