---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: demo2
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.tomcat: semver:~8.5
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
        flux.weave.works/automated: "true"
    spec:
      containers:
      - name: tomcat
        image: sshaik/tomcat:8.5.66
        ports:
        - containerPort: 8080
