apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: demo2
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
        flux.weave.works/automated: "true"
    spec:
      containers:
      - name: tomcat
        image: tomcat:8.5.55-jdk11
        ports:
        - containerPort: 8080
