apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo2
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: podinfo2
        flux.weave.works/automated: "true"
    spec:
      containers:
      - name: podinfo2
        image: quay.io/stefanprodan/podinfo:3.0.0
        ports:
        - containerPort: 3000
